# base image
FROM python:3.7.2-alpine

# install dependencies
RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd


# set working directory
#RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add and install requirements
COPY ./requirements-dev.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# add entrypoint.sh for bringing postgresql up
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh

RUN ls -al /usr/src/app/
RUN chmod +x /usr/src/app/entrypoint.sh
RUN ls -al /usr/src/app/

# add app
COPY . /usr/src/app
#RUN pip list

# run server
CMD ["/usr/src/app/entrypoint.sh"]